apiVersion: v1
kind: Service
metadata:
  name: eureka-http
  labels:
    app: eureka-http
  namespace: default
spec:
  ports:
    - port: 8101
      protocol: TCP
      targetPort: 8101
      nodePort: 30101
  selector:
    app: eureka
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-svc
  labels:
    app: eureka-svc
  namespace: default
spec:
  clusterIP: None
  ports:
    - port: 8101
      protocol: TCP
      targetPort: 8101
  selector:
    app: eureka
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-filebeat-config
  namespace: default
data:
  filebeat.yml: |-
    filebeat.prospectors:
    - type: log
      paths:
        - /app-log/*.log
      multiline:
        pattern: '^[0-9]{4}-(((0[13578]|(10|12))-(0[1-9]|[1-2][0-9]|3[0-1]))|(02-(0[1-9]|[1-2][0-9]))|((0[469]|11)-(0[1-9]|[1-2][0-9]|30)))' 
        negate:  true
        match:   after
    output.elasticsearch:
      hosts: ["124.17.100.239:9200"]
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: eureka
  namespace: default
spec:
  selector:
    matchLabels:
      app: eureka
  serviceName: "eureka-svc"
  replicas: 2
  template:
    metadata:
      labels:
        app: eureka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE # 传入当前命名空间
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_IN_SERVICE_NAME # 因为pod 通过域名互相访问，需要使用headless 服务名称
              value: eureka-svc
            - name: EUREKA_APPLICATION_NAME
              value: "eureka"
            - name: EUREKA_REPLICAS
              value: "2"
          image: 124.17.100.180:8084/eureka:vBUILD_NUMBER
          imagePullPolicy: IfNotPresent
          name: eureka-container
          ports:
            - containerPort: 8101
              protocol: TCP
          volumeMounts:
            - name: app-logs
              mountPath: /opt/app/dtt_service/applog
        - name: filebeat
          image: docker.elastic.co/beats/filebeat-oss:6.5.0
          imagePullPolicy: IfNotPresent
          args: [
            "-c", "/etc/filebeat.yml",
            "-e",
          ]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: app-logs
              mountPath: /app-log
            - name: eureka-filebeat-config
              mountPath: /etc/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: eureka-filebeat-config
          configMap:
            name: eureka-filebeat-config
      imagePullSecrets:
        - name: regsecret
