spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@124.17.100.246:1521:PROD
    username: isump
    password: c7KmG4Brm6dgsAss
     # 使用druid数据源
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#   jpa:
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
#         globally_quoted_identifiers: true
#     hibernate:
#       ddl-auto: update
#       format_sql : true


#mybatis mapper文件的位置
mybatis-plus:
    mapper-locations: classpath:com/deloitte/services/isump/**/mapper/xml/*.xml
