apiVersion: v1
kind: Service
metadata:
  name: srpmp-svc
  labels:
    app: srpmp-svc
  namespace: default
spec:
  clusterIP: None
  ports:
    - port: 8401
      protocol: TCP
      targetPort: 8401
  selector:
    app: srpmp
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: srpmp-http
  labels:
    app: srpmp-http
  namespace: default
spec:
  ports:
    - port: 8401
      protocol: TCP
      targetPort: 8401
      nodePort: 30007
  selector:
    app: srpmp
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: srpmp-filebeat-config
  namespace: default
data:
  filebeat.yml: |-
    filebeat.prospectors:
    - type: log
      paths:
        - /app-log/*.log
      multiline:
        pattern: '^[0-9]{4}-(((0[13578]|(10|12))-(0[1-9]|[1-2][0-9]|3[0-1]))|(02-(0[1-9]|[1-2][0-9]))|((0[469]|11)-(0[1-9]|[1-2][0-9]|30)))' 
        negate:  true
        match:   after
    output.elasticsearch:
      hosts: ["124.17.100.239:9200"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srpmp
  namespace: default
spec:
  selector:
    matchLabels:
      app: srpmp
  replicas: 2
  template:
    metadata:
      labels:
        app: srpmp
    spec:
      containers:
        - name: srpmp-contaner
          image: 124.17.100.180:8084/srpmp:vBUILD_NUMBER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8401
              protocol: TCP
          volumeMounts:
            - name: app-logs
              mountPath: /opt/app/dtt_service/applog
        - name: filebeat
          image: docker.elastic.co/beats/filebeat-oss:6.5.0
          imagePullPolicy: IfNotPresent
          args: [
            "-c", "/etc/filebeat.yml",
            "-e",
          ]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: app-logs
              mountPath: /app-log
            - name: srpmp-filebeat-config
              mountPath: /etc/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: srpmp-filebeat-config
          configMap:
            name: srpmp-filebeat-config
      imagePullSecrets:
        - name: regsecret