spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@124.17.100.184:1521:TEST
    username: pumc_fssc
    password: pumc_fssc
     # 使用druid数据源
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20



#mybatis mapper文件的位置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml,classpath:com/deloitte/services/fssc/**/mapper/xml/*.xml
#EBS入账地址
avToEbs: http://124.17.100.186:8010/
##收款单 收入认领 跳转地址
rep:
  cliam:
    url: http://124.17.100.183:30080/fssc/index.html#/paymentConfirmDetail
#bpm审批人配置
bpm:
  fssc:
    cwc_code: 1001011