context:
  listener:
    classes: com.deloitte.platform.common.core.monitor.ApplicationEventListener
endpoints:
  shutdown:
    enabled: true
    #禁用密码验证
    sensitive: false

#自定义超时时间
hystrix:
  command:
    #自定义的commandKey。 Feign客户端中的某方法超时时间定成9秒(格式是类名#方法名()，如果方法有入参，也要把入参的类型拼上)
    "UserDemoFeignService#get()":
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000
demo-mybatis-auto:
  ribbon:
    ConnectTimeout: 5000
    ReadTimeout: 5000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/visa_test?useUnicode\=true&characterEncoding\=utf-8
    username: root
    password: root
    # 使用druid数据源
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #消息队列服务
  rabbitmq:
    host: ${RABBIT_MQ_HOST:118.24.20.245}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:jack}
    password: ${RABBIT_MQ_PASSWORD:jack}
    publisher-confirms: true
    virtual-host: /
  #redis配置
  redis:
    host: ${REDIS_HOST:118.24.20.245}
    port: ${REDIS_PORT:6379}
#   jpa:
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
#         globally_quoted_identifiers: true
#     hibernate:
#       ddl-auto: update
#       format_sql : true



mybatis-plus:
  mapper-locations: classpath*:com.deloitte.services.*.mapper
  global-config:
    banner: false
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.deloitte.services.*.po
#  #MyBatis 的执行器配置  SIMPLE,REUSE,BATCH
#  executor-type: simple
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #是否自动刷新 Mapper 对应的 XML 文件,默认不自动刷新。生产环境关闭
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    #序列接口实现类配置
#    #key-generator: com.baomidou.springboot.xxx
#    #逻辑删除配置
#    #logic-delete-value: 0
#    #logic-not-delete-value: 1
#    #自定义填充策略接口实现
#    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
#    #自定义SQL注入器
#    #sql-injector: com.baomidou.springboot.xxx
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    #不加这个查询数据为空时，字段将被隐藏
