# 文件服务器
fdfs:
  soTimeout: 1501
  connectTimeout: 601
  # 缩略图生成参数
  thumbImage:
    width: 150
    height: 150
  trackerList:
     - 124.17.100.241:22122
  webServerUrl: http://124.17.100.241:8888/

file-service:
  upload-location: file_temp/ #零时文件存放目录

---
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@124.17.100.184:1521:TEST
    username: bpm
    password: bpm
    # 使用druid数据源
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#mybatis mapper文件的位置
mybatis-plus:
  mapper-locations: classpath:com/deloitte/platform/basic/**/mapper/xml/*.xml