spring:
  activiti:
    enableSchemaUpdate: true
    databaseType: mysql
    fontName: 正楷
    annotationFontName: 正楷
    labelFontName: 正楷
    activityFontName: 正楷
    enableRunAllTasks: false
    #是否校验process目录
    #check-process-definitions: false

---
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@124.17.100.184:1521:TEST
    username: bpm
    password: bpm
     # 使用druid数据源
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#mybatis mapper文件的位置
mybatis-plus:
  mapper-locations: classpath:com/deloitte/platform/basic/**/mapper/xml/*.xml